COM-962: Improve UI/UX of target group page
vivid-planet/comet-brevo-module pull request #64
Opened 2024-07-30 08:54 UTC by juliawegmayr

-   [ ] Add changeset (if necessary)

- Add dialog to create a new target group. After creating, the user will be redirected to the editPage. 
- Setting filters is now optional, when creating a target group. 

The possibility to pass no filters at all, still has to be checked and will be added in a follow-up PR. 

https://github.com/user-attachments/assets/9d81016a-a535-46dd-9299-0b6d2884d918

2024-07-31 07:32 UTC, RainbowBunchie commented
@juliawegmayr you should also remove the create from the previous create/update form since the create should only be possible with the dialog right?

2024-07-31 07:33 UTC, RainbowBunchie requested changes

2024-07-31 07:33 UTC, RainbowBunchie commented on packages/admin/src/targetGroups/TargetGroupDialog.tsx
> +export function TargetGroupDialog({ scope, open, handleClose }: FormProps): React.ReactElement {
```
export function TargetGroupDialog({ scope, open, handleClose }: TargetGroupDialogProps): React.ReactElement {
```

2024-07-31 07:33 UTC, RainbowBunchie commented on packages/admin/src/targetGroups/TargetGroupDialog.tsx
> +        <Dialog open={open} onClose={handleClose} maxWidth="sm">
Comet has an EditDialog component which could be used here 
https://comet-admin.netlify.app/?path=/story/stories-components-editdialog-edit-dialog--edit-dialog

2024-08-06 11:06 UTC, raphaelblum submitted a review, later dismissed

2024-08-06 12:20 UTC, RainbowBunchie commented on packages/admin/src/targetGroups/TargetGroupForm.tsx
> +        if (!id) {
The id cannot be undefined here right? Should be required in the props.

2024-08-06 13:00 UTC, RainbowBunchie submitted a review, later dismissed

2024-08-06 13:53 UTC, raphaelblum approved these changes

2024-08-06 14:13 UTC, raphaelblum approved these changes

2024-08-06 14:14 UTC, merged